name: lora-sweep
method: bayes
metric:
  name: val_accuracy
  goal: maximize
parameters:
  learning_rate:
    distribution: log_normal
    mu: -9.2103  # log(1e-4)
    sigma: 1.5174  # sqrt(log(10))
  weight_decay:
    distribution: log_normal
    mu: -6.9078  # log(1e-3)
    sigma: 1.5174
  gradient_accumulation_steps:
    values: [1, 2, 4]
  lora_alpha:
    values: [16, 32, 64]
  r:
    values: [8, 16, 32]
  lora_dropout:
    distribution: log_normal
    mu: -2.3026  # log(0.1)
    sigma: 1.1774  # sqrt(log(2))

